# Generated by Django 4.2.3 on 2023-07-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_user_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
